### ISSUE TITLE
Reprojection Error with Test Data (LS7-SR Data)

### ISSUE THREAD

**Issue by Wadhva** [ceos-seo/data_cube_ui#16]
During Step: Testing the Indexed Data
On Python console:
`data_full = dc.load(product='ls7_collections_sr_scene', output_crs='EPSG:4326', resolution=(-0.00027,0.00027))`
gives error
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/lib/python3.6/site-packages/datacube/api/core.py", line 317, in load
    geobox = geometry.GeoBox.from_geopolygon(query_geopolygon(**query) or get_bounds(observations, crs),

  File "/opt/anaconda3/lib/python3.6/site-packages/datacube/api/core.py", line 582, in get_bounds
    left = min([d.extent.to_crs(crs).boundingbox.left for d in datasets])
  File "/opt/anaconda3/lib/python3.6/site-packages/datacube/api/core.py", line 582, in <listcomp>
    left = min([d.extent.to_crs(crs).boundingbox.left for d in datasets])
  File "/opt/anaconda3/lib/python3.6/site-packages/datacube/utils/geometry.py", line 465, in to_crs
    clone.Transform(transform)
  File "/opt/anaconda3/lib/python3.6/site-packages/osgeo/ogr.py", line 7310, in Transform
    return _ogr.Geometry_Transform(self, *args)
TypeError: in method 'Geometry_Transform', argument 2 of type 'OSRCoordinateTransformationShadow *'
`
All earlier steps were successful with expected output as per your documents.
Kindly suggest a solution/workaround.

**Comment by Wadhva** [comment]
It was libproj.so issue that was causing this error. GDALTRANSFORM was not able to run. Library Path modified to include librpoj.so and the issue resolved.
